# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthyWorldSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Navajo-Swift'

  # Pods for HealthyWorldSwiftUI

  target 'HealthyWorldSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HealthyWorldSwiftUIUITests' do
    # Pods for testing
  end

end
